gsettings set org.gnome.desktop.interface clock-show-date true
gsettings set org.gnome.desktop.interface font-name "Cantarell 11"
gsettings set org.gnome.desktop.interface gtk-theme "Numix-Frost-Light"
gsettings set org.gnome.desktop.interface icon-theme "Numix-Square"
gsettings set org.gnome.desktop.background color-shading-type "solid"
gsettings set org.gnome.desktop.background primary-color "#000000"
gsettings set org.gnome.desktop.background secondary-color "#000000"
gsettings set org.gnome.desktop.background picture-options "zoom"
gsettings set org.gnome.desktop.background picture-uri "file:///usr/share/backgrounds/Digitalix-bg.png"
gsettings set org.gnome.shell enabled-extensions "['user-theme@gnome-shell-extensions.gcampax.github.com']"
gsettings set org.gnome.shell favorite-apps "[]"
gsettings set org.gnome.shell.extensions.user-theme name "Numix-Frost-Light"
exec gnome-session

